Bump bimap upper bound to <0.6
input-output-hk/ouroboros-consensus pull request #184
Opened 2023-06-27 15:26 UTC by carbolymer

# Description
Prerequisite of: https://github.com/input-output-hk/cardano-api/pull/80

2023-06-28 12:35 UTC, dnadales commented on ouroboros-consensus-cardano/ouroboros-consensus-cardano.cabal
> -version:         0.6.1.0
This is not necessary.

2023-06-28 12:36 UTC, dnadales requested changes
Thanks for the PR. We should not update the package version though.

2023-06-28 14:51 UTC, carbolymer commented on ouroboros-consensus-cardano/ouroboros-consensus-cardano.cabal
> -version:         0.6.1.0
removed

2023-06-28 14:51 UTC, carbolymer commented on ouroboros-consensus/ouroboros-consensus.cabal
> -version:         0.8.0.0
removed

2023-06-29 09:25 UTC, dnadales approved these changes

2023-06-29 10:42 UTC, merged