Trace backing store events
input-output-hk/ouroboros-consensus pull request #232
Opened 2023-07-13 15:54 UTC by jasagredo

# Description

Do this in consensus instead of polluting the tracing code too much with low level stuff. 

Part of #227

2023-07-14 10:28 UTC, jorisdral requested changes

2023-07-17 13:43 UTC, jasagredo commented on ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/BackingStore/InMemory.hs
> +  | TVarTraceInitialisedFromSnapshot  !FS.FsPath
Done

2023-07-17 13:43 UTC, jasagredo commented on ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/BackingStore/InMemory.hs
> +  | TVarTraceInitialisingFromValues !(WithOrigin SlotNo)
Done

2023-07-17 13:43 UTC, jasagredo commented on ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/BackingStore/InMemory.hs
> +data TVarTraceEvent =
Done

2023-07-17 13:44 UTC, jasagredo commented on ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/BackingStore/InMemory.hs
> +showTrace (TVarTraceWrite sl1 sl2) = "Wrote to InMemory backing store up to slot " <> showT sl2 <> " onto " <> showT sl1
Done

2023-07-17 13:44 UTC, jasagredo commented on ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/BackingStore/LMDB.hs
> +showTrace (TDBWrite sl1 sl2)  = "Wrote to LMDB up to slot " <> showT sl2 <> " onto " <> showT sl1
Done

2023-07-17 13:45 UTC, jorisdral approved these changes

2023-07-17 13:49 UTC, merged