Re-enable completeness warnings in GHC>=9.6
input-output-hk/ouroboros-consensus pull request #829
Opened 2023-12-12 17:22 UTC by fraser-iohk

Partially fixes #592 

- `Re-enable completeness warnings in Ouroboros.Consensus.Cardano.Node only on GHC>=9.6`

# Description

This change adds back the disabled warnings provided by the completeness checker which were turned off due to the impact they had on compile times (https://github.com/input-output-hk/ouroboros-network/commit/3a6cd9760c32dd53ebf567d6a83feab633cebfe4). In future, once we no longer support GHC 8.10.x, we should remove the flag entirely and close the associated ticket.

2023-12-13 08:37 UTC, jasagredo approved these changes
👌

2023-12-13 11:11 UTC, jasagredo requested changes

2023-12-14 16:34 UTC, fraser-iohk commented on ouroboros-consensus-cardano/changelog.d/20231212_174729_fraser.murray_warning_cpp_conditional.md
> +- Re-enable completeness warnings in Ouroboros.Consensus.Cardano.Node only on GHC>=9.6
I don't mind this being in the changelog, but I don't have strong feelings either way

I don't understand what you mean by the message being the opposite, though -- the change turns the warning checks back on on versions greater than 9.6, which seems to be correct afaict (?)

2023-12-14 19:01 UTC, jasagredo commented on ouroboros-consensus-cardano/changelog.d/20231212_174729_fraser.murray_warning_cpp_conditional.md
> +- Re-enable completeness warnings in Ouroboros.Consensus.Cardano.Node only on GHC>=9.6
Ah yes indeed I was confused. It is >=9.6 yeah

2023-12-15 13:37 UTC, merged